import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ModalProvider } from "@context/modal-context";

const pretendard = localFont({
  src: "/fonts/pretendard-variable.woff2",
  display: "swap",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} antialiased tracking-tighter`}
      >
        <div className="max-w-[480px] min-h-screen mx-auto border-x-[1px] border-[#F2F2F2] box-content">
          <ModalProvider>{children}</ModalProvider>
        </div>
      </body>
    </html>
  );
}
